# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weexdemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    
    pod 'WeexSDK'

  # Pods for weexdemo

  target 'weexdemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weexdemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
